include: package:flutter_lints/flutter.yaml

# https://dart-lang.github.io/linter/lints/index.html.
linter:
  rules:
    avoid_redundant_argument_values: true
    use_super_parameters: true
    directives_ordering: true
    sort_constructors_first: true
