name: notified_preferences
description: A wrapper around sharedpreferences which provides a valuenotifier for each preference.
version: 2.0.1
homepage: https://github.com/clragon/notified_preferences

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  runtime_type: ^1.0.1
  shared_preferences: ">=2.0.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.21.4
